directories:
  output: release
  buildResources: build
appId: com.infernix.executor
productName: Infernix
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - bin/**/*
extraResources:
  - from: bin
    to: bin
    filter:
      - '**/*'
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/icon.ico
nsis:
  oneClick: true
  perMachine: false
  allowToChangeInstallationDirectory: false
  installerIcon: build/icon.ico
  uninstallerIcon: build/icon.ico
  installerHeaderIcon: build/icon.ico
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Infernix
  include: build/installer.nsh
  installerHeader: build/installerHeader.bmp
  installerSidebar: build/installerSidebar.bmp
  uninstallerSidebar: build/installerSidebar.bmp
  license: build/license.txt
  warningsAsErrors: false
electronVersion: 40.1.0
